apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: passgen
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: quay.io/gbsalinetti/passgen
    generation: 1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source

