{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ include "passgen.fullname" . }}
  name: {{ include "passgen.fullname" . }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  host: {{ .Values.route.host }}
  port:
    targetPort: {{ .Values.route.targetPort }}
  tls:
    termination: passthrough
  to:
    kind: Service
    name: {{ include "passgen.fullname" . }}
    weight: 100
  wildcardPolicy: None
{{- end }}
